dependencies:
  - name: mongodb
    version: "~ 7.14.2"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: postgresql
    version: ">= 0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
