apiVersion: v1
kind: Secret
metadata:
  name: {{ template "discourse.fullname" . }}
  labels: {{- include "discourse.labels" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "discourse.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "discourse.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.discourse.password }}
  discourse-password: {{ .Values.discourse.password | b64enc | quote }}
  {{- else }}
  discourse-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}

  {{- if not .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  postgresql-postgres-password: {{ .Values.externalDatabase.postgresqlPostgresPassword | b64enc | quote }}
  {{- end }}

  {{- if and (not .Values.redis.enabled) (not (empty .Values.externalRedis.password)) }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
