apiVersion: v1
name: node
version: 12.0.1
appVersion: 10.21.0
description: Event-driven I/O server-side JavaScript environment based on V8
keywords:
  - node
  - javascript
  - nodejs
  - git
home: http://nodejs.org/
sources:
  - https://github.com/bitnami/bitnami-docker-node
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/nodejs/img/nodejs-stack-110x117.png
annotations:
  category: Infrastructure
